### ISSUE TITLE
ctlptl get takes a long time

### ISSUE THREAD

**Issue by chrislovecnm** [tilt-dev/ctlptl#113]
When you have other entries in your kubeconfig which may no longer exist, ctlptl is taking a very long time to list the results.  We often have dirty kubeconfig files, so this is a bit of an odd user experience.

```bash
$ time ctlptl get
CURRENT   NAME                                               PRODUCT   AGE       REGISTRY
          foo   gke       unknown   none
          bar gke       unknown   none
          gca        gke       unknown   none
          tw    gke       unknown   none
*         kind-kind                                          kind      6m        localhost:56978
ctlptl get  0.13s user 0.15s system 0% cpu 1:00.46 total
```

I have four gke clusters in my kubeconfig, and I think two of them still exist.

**Comment by nicks** [comment]
thanks for the report! ya, i can repro, it looks like it just hangs if the cluster is dead... :(

**Comment by chrislovecnm** [comment]
@nicks I have not dug through the code, but I assume you are making a k8s API call?  What about just making an HTTP call to see if the endpoint is alive?  Real quick timeout?

**Comment by nicks** [comment]
ya, we're using the go k8s client. Want to figure out which HTTP call it's hanging on - in theory, it should already be doing that kind of check!

**Comment by chrislovecnm** [comment]
@nicks yes it does that check, but the HTTP client with client-go has a VERY long timeout, by default as design, you can override the timeout though.
