### ISSUE TITLE
If socat is not installed kind is not started

### ISSUE THREAD

**Issue by chrislovecnm** [tilt-dev/ctlptl#115]
1. install from master
2. use a system (osx or wsl2) that does not have socat
3. run:

```bash
# clove @ DESKTOP-6TGAFKG in ~/Workspace/src/github.com/tilt-dev/ctlptl/examples on git:main o [14:15:49] C:130
$ ctlptl apply -f kind.yaml
Creating registry "ctlptl-registry"...
 🎮 Env DOCKER_HOST set. Assuming remote Docker and forwarding registry to localhost:34131
creating local portforwarder: exec: "socat": executable file not found in $PATH
```

You get the registry started but not kind:
```bash
# clove @ DESKTOP-6TGAFKG in ~/Workspace/src/github.com/tilt-dev/ctlptl/examples on git:main o [14:16:52]
$ docker ps
CONTAINER ID   IMAGE          COMMAND                  CREATED          STATUS          PORTS                                         NAMES
698c07f443c5   alpine/socat   "/bin/sh -c 'while t…"   19 seconds ago   Up 18 seconds                                                 ctlptl-portforward-service
ab2fa4a07466   registry:2     "/entrypoint.sh /etc…"   21 seconds ago   Up 21 seconds   0.0.0.0:34131->5000/tcp, :::34131->5000/tcp   ctlptl-registry
```

**Comment by nicks** [comment]
Hmmm...what do you have `DOCKER_HOST` set to?

`ctlptl` tries to detect when you're running Kind on a remote docker machine, and tries to set up port-forwarding so that you can connect to Kind as if it was running on the current host. (That's what we're using socat for).

We should improve the error message here, but also, that doesn't sound like the setup you're trying to do?

**Comment by chrislovecnm** [comment]
```
$ echo $DOCKER_HOST
unix:///var/run/docker.sock
```

**Comment by chrislovecnm** [comment]
I unset that and the pull and push seem easier.

**Comment by nicks** [comment]
AHHHH ya, I understand what's going on. It's getting confused because you're on Windows and it's comparing against the default Windows docker host. ya, we can fix this
