### ISSUE TITLE
k3d support

### ISSUE THREAD

**Issue by pragmaticivan** [tilt-dev/ctlptl#128]
It appears k3d might be a good fit now that it supports local registry?

**Comment by nicks** [comment]
Yes! I worked with k3d a bit on their local registry stuff. TBQH, I thought that the k3d registry CLI was so good and so close to what ctlptl already does, that i was on the fence about whether it was worth adding a separate k3d manager in ctlptl.

what do you think? are there things ctlptl adds that would be worth it anyway?

**Comment by pragmaticivan** [comment]
That fits this goal:
```
To interoperate well with all local Kubernetes solutions, including docker-desktop, kind, minikube, k3d, or microk8s
```

On a team where ctlptl would use one CLI and pick their own `poinson` on how to run their k8s cluster.

**Comment by nicks** [comment]
makes sense to me :+1:

**Comment by nicks** [comment]
added in https://github.com/tilt-dev/ctlptl/pull/171, will do a release soon
