### ISSUE TITLE
Support DOCKER_HOST remote environments

### ISSUE THREAD

**Issue by chrisgoffinet** [tilt-dev/ctlptl#132]
I am running `ctlptl` on macOS, but I've noticed that there are some assumptions being made that Docker Desktop has to be running. Would it be possible to support `DOCKER_HOST` ? That way we aren't tied to using the `unix:///var/run/docker.sock` ?

**Comment by nicks** [comment]
thanks for the report! Ya, that seems reasonable - we should be able to detect if you're not talking to docker-desktop, and skil the docker-desktop setup

**Comment by nicks** [comment]
should be fixed in v0.5.7! verified with a KIND cluster running inside a Minikube VM :upside_down_face:

**Comment by winmillwill** [comment]
seems not:

```
$ export DOCKER_HOST=$HOME/.colima/docker.sock; cat <<EOF | ctlptl apply -f -
apiVersion: ctlptl.dev/v1alpha1
kind: Cluster
product: kind
registry: ctlptl-registry
EOF
unable to parse docker host `/Users/williammilton/.colima/docker.sock`

$ export DOCKER_HOST=unix://$HOME/.colima/docker.sock; cat <<EOF | ctlptl apply -f -
apiVersion: ctlptl.dev/v1alpha1
kind: Cluster
product: kind
registry: ctlptl-registry
EOF
reading docker-desktop settings: status code 404

$ export DOCKER_HOST=unix:///$HOME/.colima/docker.sock; cat <<EOF | ctlptl apply -f -
apiVersion: ctlptl.dev/v1alpha1
kind: Cluster
product: kind
registry: ctlptl-registry
EOF
reading docker-desktop settings: status code 404

$ ctlptl version
v0.5.7, built 2021-09-29
```

**Comment by nicks** [comment]
@winmillwill hmmm...can you share a little bit more about what you're trying to do? 

This issue is "Support DOCKER_HOST remote environments". Sounds like you're trying to do something very different, e.g., set up a local Unix docker socket that looks like Docker Desktop but isn't Docker Desktop...might be worth filing a separate issue with more context.
