### ISSUE TITLE
ip address clash when using minikube

### ISSUE THREAD

**Issue by lizzthabet** [tilt-dev/ctlptl#144]
When using `ctlptl` with `minikube`, Tim Loyer encountered an issue with Docker assigning IP addresses in the order that containers are created. Tim said:

> I'm running into an issue but I am not sure if it is a ctlptl problem or minikube+docker driver issue. If create a minikube cluster with ctlptl, restart my computer (or stop minikube container and restart ctlptl-registry) and then try to start minikube again, minikube will fail saying that the container stopped running. It ends up this is because the IP address (192.168.49.2) has been taken over by ctlptl-registry and is already in use when minikube tries to use it for itself.

@milas was able to reproduce the issue locally:

> I think minikube is launching itself with `--network minikube --ip 192.168.49.2` and ctlptl is launching the registry with `--network minikube` (but no IP flag)
> Docker DHCP isn’t smart enough to not hand out IP addresses “reserved” by created (but not yet running containers), so if the registry starts first, it assigns it 192.168.49.2, at which point the minikube container can’t be started up again

One solution might be for `ctlptl` to choose a fixed (but random) IP that doesn't conflict when it's running with `minikube`.

[Full thread on k8s slack](https://kubernetes.slack.com/archives/CESBL84MV/p1632935796214000) for reference.

**Comment by nicks** [comment]
i poked around this a bit. the problem is that minikube hard-codes the IP address based on the number of machines:

https://github.com/kubernetes/minikube/blob/master/pkg/drivers/kic/kic.go#L101

so we would need to also hardcode the ip adress of the registry that's living alongside minikube

**Comment by nicks** [comment]
this is a good description of the upstream issue: https://github.com/kubernetes/minikube/issues/13729

**Comment by adinhodovic** [comment]
Still seeing this issue even with the workaround above. Rebooting my linux(same happening with macs) machine and running `ctlptl apply -f ./cluster.yml`, tears down the cluster after the error and recreates it which is not preferred.

```
Cluster "minikube" exists but is stopped. Starting...
😄  minikube v1.25.2 on Arch
🆕  Kubernetes 1.23.3 is now available. If you would like to upgrade, specify: --kubernetes-version=v1.23.3
✨  Using the docker driver based on existing profile
👍  Starting control plane node minikube in cluster minikube
🚜  Pulling base image ...
🔄  Restarting existing docker container for "minikube" ...
🤦  StartHost failed, but will try again: provision: get ssh host-port: unable to inspect a not running container to get SSH port
🔄  Restarting existing docker container for "minikube" ...
😿  Failed to start docker container. Running "minikube delete" may fix it: provision: get ssh host-port: unable to inspect a not running container to get SSH port

❌  Exiting due to GUEST_PROVISION_CONTAINER_EXITED: Docker container exited prematurely after it was created, consider investigating Docker's performance/health.

Deleting cluster minikube to initialize with registry ctlptl-registry
🔥  Deleting "minikube" in docker ...
🔥  Deleting container "minikube" ...
🔥  Removing /home/adin/.minikube/machines/minikube ...
💀  Removed all traces of the "minikube" cluster.
😄  minikube v1.25.2 on Arch
✨  Using the docker driver based on user configuration
👍  Starting control plane node minikube in cluster minikube
🚜  Pulling base image ...
🔥  Creating docker container (CPUs=2, Memory=7900MB) ...
📦  Preparing Kubernetes v1.22.4 on containerd 1.4.12 ...
    ▪ kubelet.max-pods=500
    ▪ kubelet.housekeeping-interval=5m
    ▪ kubelet.cni-conf-dir=/etc/cni/net.mk
    ▪ Generating certificates and keys ...
    ▪ Booting up control plane ...
    ▪ Configuring RBAC rules ...
🔗  Configuring CNI (Container Networking Interface) ...
🔎  Verifying Kubernetes components...
    ▪ Using image gcr.io/k8s-minikube/storage-provisioner:v5
🌟  Enabled addons: storage-provisioner, default-storageclass

❗  /usr/bin/kubectl is version 1.24.1, which may have incompatibilites with Kubernetes 1.22.4.
    ▪ Want kubectl v1.22.4? Try 'minikube kubectl -- get pods -A'
🏄  Done! kubectl is now configured to use "minikube" cluster and "default" namespace by default
Switched to context "minikube".
 🔌 Connected cluster minikube to registry ctlptl-registry at localhost:43973
 👐 Push images to the cluster like 'docker push localhost:43973/alpine'
cluster.ctlptl.dev/minikube created
```
