### ISSUE TITLE
installation with go get

### ISSUE THREAD

**Issue by CezaryTarnowski-TomTom** [tilt-dev/ctlptl#157]
maybe it would be handy to clearly state in the INSTALL.md the possibility to install the tool with:
```
go install github.com/tilt-dev/ctlptl/cmd/ctlptl@latest
```

**Comment by CezaryTarnowski-TomTom** [comment]
the only thing weird after installing it with go is the behavior of the version command
```
$ ctlptl version
v0.0.0-main, built unknown
```

**Comment by nicks** [comment]
makes sense to me! want to send a PR?

ya, for CLI tools, the convention i've seen a lot is to set the version at build time like `-X main.version=... -X main.date=...`

something like `-X main.version=dev -X main.date=$(date --rfc-3339=date)`

**Comment by CezaryTarnowski-TomTom** [comment]
for the installation with go install, instead of injecting the version on build time, it would be better to get that from debug.ReadBuildInfo

this would keep the install command clean

**Comment by CezaryTarnowski-TomTom** [comment]
as ko failed to install on e2e pipeline I've also bumped go to 1.17 in tests and tidy go.mod

**Comment by CezaryTarnowski-TomTom** [comment]
it looks nice when I've installed it from the main:
```
$ go install github.com/tilt-dev/ctlptl/cmd/ctlptl@main
go: downloading github.com/tilt-dev/ctlptl v0.6.2-0.20211207215729-304c33f52ee8
$ ctlptl version
vv0.6.2-0.20211207215729-304c33f52ee8, built unknown
```
nevertheless, until the next release is done, the documentation is not entirely true as the @latest points to the last release

**Comment by nicks** [comment]
just did a release!
