### ISSUE TITLE
cannot load io/fs

### ISSUE THREAD

**Issue by rotten** [tilt-dev/ctlptl#161]
I cloned the repo and ran "make install" on an Ubuntu 20.04 system.

After downloading and unpacking a ton of go packages it throws this error:
```
build github.com/tilt-dev/ctlptl/cmd/ctlptl: cannot load io/fs: malformed module path "io/fs": missing dot in first path element

```
Is there anything else I should do to get it to build?

**Comment by nicks** [comment]
i think this usually means you have an old version of Go. Are you on Go 1.17?

**Comment by rotten** [comment]
I just went with the Ubuntu golang package, version 1.13.8.

I'll see if I can upgrade and try again.

**Comment by rotten** [comment]
Yes, that was it.  I switched from the `apt` go to the `snap` go, and I was able to build ctlptl.  Thanks.
