### ISSUE TITLE
ctlptl is not starting with minikube 1.25.1 and docker desktop 4.4.4

### ISSUE THREAD

**Issue by drano** [tilt-dev/ctlptl#184]
I am using this command "ctlptl create cluster minikube --registry=ctlptl-registry --min-cpus=4 --kubernetes-version=v1.21.2"
ctlptl is running indefinitely without logs 

It was ok with minikube 1.25.1 but not after update to docker desktop 4.4.4

With command "minikube start", minikube is starting correctly but not when using ctlptl

**Comment by drano** [comment]
ctlplt seems to have some problems to connect to docker desktop (windows version). 
The command "ctlptl docker-desktop settings" is running indefinitely without logs

**Comment by nicks** [comment]
thanks for reporting! I think i understand the problem - docker desktop changed their socket protocol a bit - but also want to dig into why it's hanging rather than erroring

**Comment by nicks** [comment]
should be fixed in https://github.com/tilt-dev/ctlptl/pull/185, which i'm releasing now as ctlptl v0.7.4
