### ISSUE TITLE
Handling of stopped clusters on `ctlptl apply`

### ISSUE THREAD

**Issue by milas** [tilt-dev/ctlptl#211]
From Tim in [Slack](https://kubernetes.slack.com/archives/CESBL84MV/p1650047186430739):

> I had this fun thing happy after rebooting and trying to start my minikube cluster again. I've found that if I use minikube stop followed by ctlptl apply -f (my cluster config) then it will delete my cluster rather than confirming it exists and starting it. I'm not sure whether ctlptl ought to be used to start a cluster, but I did find that it was better than minikube start in some cases as ctlptl re-patches the containerd registry mirror. What is the correct way to restart a minikube cluster after reboot? Is this a bug or am I misusing it?
> ```
> ctlptl apply -f cluster.yaml
> Deleting cluster minikube to initialize with registry ctlptl-registry
> 🔥  Deleting "minikube" in docker ...
> 🔥  Deleting container "minikube" ...
> 🔥  Removing /home/tim/.minikube/machines/minikube ...
> 💀  Removed all traces of the "minikube" cluster.
> ...
> ```

Ignoring the containerd patching hack/issue for minikube, this isn't a hugely unusual use case to to `apply` and expect `ctlptl` to launch an existing, yet stopped, local cluster tool.

We should think about if there's common scenarios where we _can_ handle this (though there's some chicken-and-egg problems, e.g. we can't read local registry info until we start the cluster, so we might end up starting it and then realizing we can't reconcile it in-place and needing to delete it, which would take longer than just having done that in the first place!)

Otherwise, it might be a good idea to clarify the behavior in the README a bit.

**Comment by nicks** [comment]
ya, ctlptl doesn't really have any knowledge right now of stopped clusters, but should be straightforward enough to add
