### ISSUE TITLE
k3d config options

### ISSUE THREAD

**Issue by krancour** [tilt-dev/ctlptl#224]
Loving ctlptl! Nice work!

It would be awesome if k3d configuration options could be passed through to the `k3d cluster create` command for `product: k3d`, similar to how `kindV1Alpha4Cluster` options get passed through to the `kind create cluster` command for `product: kind`.

**Comment by nicks** [comment]
aw thanks :heart: 

Would a k3d configuration just include the flags here?
https://k3d.io/v5.2.0/usage/commands/k3d_cluster_create/
or alternatively, we could add a `CreateFlags` array like we did for minikube (https://pkg.go.dev/github.com/tilt-dev/ctlptl@v0.8.1/pkg/api#MinikubeCluster)

is this mainly to add volumes, or are there other flags that are important?

**Comment by krancour** [comment]
@nicks thanks for the response.

I hadn't thought through implementation much, tbh, but the specific use case that made me request this was adding port forwards.

**Comment by nicks** [comment]
ooh that's good to know. are you using the portforwards to test an ingress? i've been thinking about better "standard" setups for dev clusters with ingresses.

**Comment by krancour** [comment]
I'm using Tilt to hack on several different projects, but most of these projects have dependencies I'm _not_ actively hacking on and don't care to build/deploy from source since helm charts are readily available. So I'll have a make target like `dev-cluster-up` that uses ctlptl to launch the cluster and then immediately installs those prereqs. In many of those cases, it's useful for me to also be able to connect directly to those dependencies from the physical host.

Right now I can do all of this with ctlptl + kind, but k3d comes up a bit faster, so I'd be entertaining the switch if this worked.

**Comment by mjgallag** [comment]
@nicks I'd love to be able to disable `traefik`. It could be the default for `ctlptl` if you're looking to "standardize".
```yaml
apiVersion: k3d.io/v1alpha4
kind: Simple
options:
  k3s:
    extraArgs:
      - arg: --disable=traefik
        nodeFilters:
          - server:*
```
