### ISSUE TITLE
support docker for desktop linux k8s clusters

### ISSUE THREAD

**Issue by nicks** [tilt-dev/ctlptl#226]
If you try to create a docker-desktop cluster for linux, 

```
ctlptl create cluster docker-desktop
```

you'll get:

```
Detected remote DOCKER_HOST. Remote Docker engines do not support Docker Desktop clusters: unix:///home/me/.docker/desktop/docker.sock
```

Now that docker-deskop linux is out of beta, we should support this.

**Comment by nicks** [comment]
Hmmm...this still doesn't work for me? am i missing something?

```
$ ctlptl apply -f ./examples/docker-desktop.yaml 
docker-desktop Kubernetes clusters are only available on macos and windows
```

**Comment by nicksieger** [comment]
Ah, crap. There is [one more guard](https://github.com/tilt-dev/ctlptl/blob/main/pkg/cluster/admin_docker_desktop.go#L38-L41) that was missed.
