### ISSUE TITLE
Needs documentation: Option to disable Kubernetes in Docker Desktop

### ISSUE THREAD

**Issue by kbakk** [tilt-dev/ctlptl#241]
Docker Desktop supports shutting down a Kubernetes cluster, which is useful when you don't need it. The cluster can then be brought back up again, with the data intact. 

~`ctlptl docker-desktop` don't currently seem to have that option.~

~It would be nice with a command such as `ctlptl docker-desktop {disable|enable}-cluster` (or `{pause|upause}`).~

The feature is a bit hidden and should be documented: `ctlptl docker-desktop set kubernetes.enabled false` (thanks @nicks).

**Comment by nicks** [comment]
I think you can do this with:

```
ctlptl docker-desktop set kubernetes.enabled false
```

?

Tho we should add that to the docs

**Comment by kbakk** [comment]
Ah, that works for me, thanks! 

I'll change this issue to be a doc task then, so it can be closed once documented. Hope the maintainers agree. 🙂
