### ISSUE TITLE
Enable storage.delete for registry

### ISSUE THREAD

**Issue by liskin** [tilt-dev/ctlptl#247]
The local registry created by ctlptl doesn't have [deletion](https://github.com/distribution/distribution/blob/main/docs/configuration.md#delete) enabled, so tools like [tilt](https://github.com/tilt-dev/tilt) cannot garbage collect even if they wanted to (and [people certainly did request this](https://github.com/tilt-dev/tilt/issues/2102)). Can we enable deletion, e.g. by setting `REGISTRY_STORAGE_DELETE_ENABLED=true` in the registry container environment?

It should be noted, however, that for any image deletion to actually result in the associated blobs being deleted and disk space being freed, the registry garbage collector needs to be invoked afterwards. This can be performed manually:
```
docker exec -it ctlptl-registry registry garbage-collect --delete-untagged /etc/docker/registry/config.yml
```
It seems a bit weird for any downstream clients that wish to delete tags/images from the registry to manually invoke that command, though. Are there perhaps other registry implementations that handle this better? Or are we meant to build our own registry docker image that invokes this command periodically in the background?

**Comment by nicks** [comment]
sure! i think enabling REGISTRY_STORAGE_DELETE_ENABLED by default seems reasonable.
