### ISSUE TITLE
Linux install fails

### ISSUE THREAD

**Issue by douglasg14b** [tilt-dev/ctlptl#258]
When running the commands in the readme the following error occurs:

> root@DESKTOP-A37A319:~# curl -fsSL https://github.com/tilt-dev/ctlptl/releases/download/v0.8.9/ctlptl.0.8.9.linux.x86_64.tar.gz | sudo tar -xzv -C /usr/local/bin ctlptl
/usr/bin/gzip: 1: ELF: not found
/usr/bin/gzip: 3: : not found
/usr/bin/gzip: 4: Syntax error: "(" unexpected
tar: Child died with signal 13
tar: Error is not recoverable: exiting now
curl: (23) Failure writing output to destination

Problem with my env, or with the download?

**Comment by nicksieger** [comment]
I think you need the dash to indicate reading from stdin?


... | tar -zvf -C /usr/local/bin - ctlptl

**Comment by nicks** [comment]
https://askubuntu.com/questions/1417255/trying-to-unzip-a-tgz-in-wsl-but-get-elf-not-found-error

this error message means you don't have gzip installed correctly.

**Comment by douglasg14b** [comment]
Ah yep, gzip was the problem. Weird, fresh install. 

That was the ticket.
