### ISSUE TITLE
K3D schema upgrade to v1alpha5 Simple.

### ISSUE THREAD

**Issue by almereyda** [tilt-dev/ctlptl#293]
K3D have upgraded their configuration schema to v1alpha5.

- https://github.com/k3d-io/k3d/blob/main/pkg/config/v1alpha5/schema.json

Using it in a cluster configuration will yield an unmarshalling error:

```
% ctlptl apply -f k3d-cluster.yaml
visiting k3d-cluster.yaml: decoding {Cluster ctlptl.dev/v1alpha1}: yaml: unmarshal errors:
  line 12: field v1alpha5Simple not found in type api.K3DCluster
```

When switching back, K3D also suggests to migrate:

```
WARN[0000] Default config apiVersion is 'k3d.io/v1alpha5', but you're using 'k3d.io/v1alpha4': consider migrating.
```

What would be required to support the v1alpha5 Simple schema?

**Comment by nicks** [comment]
shouldn't be too hard to add, see the PR that added v1alpha4: https://github.com/tilt-dev/ctlptl/pull/265
