### ISSUE TITLE
ctlptl get registries -oname do return prefixed names

### ISSUE THREAD

**Issue by Valgard** [tilt-dev/ctlptl#309]
### Problem

If i run `ctlptl get registries -oname` then i get only following *prefixed* output:

```
registry.ctlptl.dev/ctlptl-registry-kind
```

This issue is related to #307.

### Expected

With following registries:
```
NAME                   HOST ADDRESS     CONTAINER ADDRESS   AGE
ctlptl-registry-kind   127.0.0.1:5000   172.17.0.2:5000     1m
```

I would expect the following *not prefixed* output:
```
ctlptl-registry-kind
```

For a workaround see #307.

### Output of `ctlptl version`:

```
v0.8.22, built 2023-08-30
```

**Comment by nicks** [comment]
This is working as intended. We try to maintain compatibility with `kubectl`, and in fact use the same underlying printing libraries as `kubectl`. Those libraries interpret `-o name` to `[resource]/[name]`. See: https://github.com/kubernetes/kubernetes/issues/5906
