### ISSUE TITLE
K3d config file formating

### ISSUE THREAD

**Issue by hugo-ninja** [tilt-dev/ctlptl#312]
Hi

Im trying to pass a k3d config file but it looks like im not getting the formatting correct looking to pass, any ideas on what the formatting would look like?

  k3d: # k3d runtime settings
    wait: true # wait for cluster to be usable before returning; same as `--wait` (default: true)
    timeout: "6m0s" # wait timeout before aborting; same as `--timeout 60s`
    disableLoadbalancer: true # same as `--no-lb`
    disableImageVolume: false # same as `--no-image-volume`
    disableRollback: false # same as `--no-Rollback`
  k3s: # options passed on to K3s itself
    extraArgs: # additional arguments passed to the `k3s server|agent` command; same as `--k3s-arg`
      - arg: --disable=servicelb
        nodeFilters:
          - server:*
      - arg: --disable=traefik
        nodeFilters:
          - server:*
      - arg: --tls-san=127.0.0.1
        nodeFilters:
          - server:*
      - arg: --disable-network-policy
        nodeFilters:
          - server:*
      - arg: --flannel-backend=none
        nodeFilters:
          - server:*
  kubeconfig:
    updateDefaultKubeconfig: true # add new cluster to your default Kubeconfig; same as `--kubeconfig-update-default` (default: true)
    switchCurrentContext: true # also set current-context to the new cluster's context; same as `--kubeconfig-switch-

**Comment by nicks** [comment]
did you look at the example? https://github.com/tilt-dev/ctlptl/blob/main/examples/k3d-config.yaml

when you say "im not getting the formatting correct", can you be more specific about what you tried, what you expected to happen, and what happened instead?

**Comment by hugo-ninja** [comment]
Hey Nicks thank you for the reply, I took a look at the example, I tried several variations of this config file:

`# k3d with an embedded config
apiVersion: ctlptl.dev/v1alpha1
kind: Cluster
name: k3d-testing
product: k3d
k3d:
  v1alpha4Simple:
#      network: custom-network
#      wait: true # wait for cluster to be usable before returining; same as `--wait` (default: true)
#      timeout: "6m0s" # wait timeout before aborting; same as `--timeout 60s`
#      disableLoadbalancer: true # same as `--no-lb`
#      disableImageVolume: false # same as `--no-image-volume`
#      disableRollback: false # same as `--no-Rollback`
k3s: # options passed on to K3s itself
     extraArgs: # additional arguments passed to the `k3s server|agent` command; same as `--k3s-arg`
      - arg: --disable=servicelb
        nodeFilters:
          - server:*
      - arg: --disable=traefik
        nodeFilters:
          - server:*
      - arg: --tls-san=127.0.0.1
        nodeFilters:
          - server:*
      - arg: --disable-network-policy
        nodeFilters:
          - server:*
      - arg: --flannel-backend=none
        nodeFilters:
          - server:*
#    kubeconfig:
#      updateDefaultKubeconfig: true # add new cluster to your default Kubeconfig; same as `--kubeconfig-update-default` (default: true)
#      switchCurrentContext: true # also set current-context to the new cluster's context; same as `--kubeconfig-switch-context` (default: true)`

Depending on the variation I get the following error type:

visiting k3d-config.yaml: decoding {Cluster ctlptl.dev/v1alpha1}: yaml: unmarshal errors:
  line 14: field k3s not found in type api.Cluster

I would expect it to accept the k3s arguments.

**Comment by nicks** [comment]
the error message:

```
visiting k3d-config.yaml: decoding {Cluster ctlptl.dev/v1alpha1}: yaml: unmarshal errors:
line 14: field k3s not found in type api.Cluster
```

is telling you that you got the indentation wrong and is telling you the exact line to fix. It should look something like:

```
apiVersion: ctlptl.dev/v1alpha1
kind: Cluster
name: k3d-testing
product: k3d
k3d:
  v1alpha4Simple:
      k3s: 
        extraArgs:
            ...
```

the error message is telling you which fie

**Comment by hugo-ninja** [comment]
Awesome thanks for pointing me in the right direction that worked.
