### ISSUE TITLE
Registry not reachable with fixed port

### ISSUE THREAD

**Issue by coolibre** [tilt-dev/ctlptl#317]
ctlptl version:         v0.8.22, built 2023-09-01
tilt version:             v0.22.15
kind version:          kind v0.20.0 go1.20.4 linux/amd64
docker version:      24.0.6
kind node image:  kindest/node:v1.25.11

When using a random port tilt/kind can pull the image on eg. localhost:41703/myimage.
When using a fixed port tilt/kind cant reach the registry with 

```bash
[K8s EVENT: Pod adapter-84768dd5fd-q8bsp (ns: mynamespace)] Pulling image "localhost:5005/myimage:latest"
[K8s EVENT: Pod adapter-84768dd5fd-q8bsp (ns: mynamespace)] Failed to pull image "localhost:5005/myimage:latest": rpc error: code = Unknown desc = failed to pull and unpack image "localhost:5005/myimage:latest": failed to resolve reference "localhost:5005/myimage:latest": failed to do request: Head "[http://localhost:5005/v2/myimage/manifests/latest":](http://localhost:5005/v2/myimage/manifests/latest) dial tcp [::1]:5005: connect: connection refused
```

**DOES WORK:** 
```bash
cat <<EOF | ctlptl apply -f -
apiVersion: ctlptl.dev/v1alpha1
kind: Cluster
product: kind
registry: ${cluster}-registry
kindV1Alpha4Cluster:
  name: ${cluster}
  nodes:
  - role: control-plane
    image: ${argc_kind_node_image}
    ...
EOF
```

**DOES NOT WORK:** 
```bash
  cat <<EOF | ctlptl apply -f -
apiVersion: ctlptl.dev/v1alpha1
kind: Registry
name: ${cluster}-registry
port: 5005
---
apiVersion: ctlptl.dev/v1alpha1
kind: Cluster
product: kind
registry: ${cluster}-registry
kindV1Alpha4Cluster:
  name: ${cluster}
  nodes:
  - role: control-plane
    image: ${argc_kind_node_image}
    ...
EOF
```

My overall goal is to use a fixed port to not spam "docker image ls" as we restart our dev stack quite often and i end up with the same image having multiple different RepoTags.

**Comment by nicks** [comment]
Hmmm... almost all of our integration tests use a fixed port.
https://github.com/tilt-dev/ctlptl/blob/main/test/k3d/registry.yaml

Does the problem go away if you remove your k3d config? Maybe something In there is causing the issue.

**Comment by nicks** [comment]
since we haven't heard back, i'm going to close this as not reproducible
