### ISSUE TITLE
[feature request] Consider adding support for innobead/kubefire

### ISSUE THREAD

**Issue by DerekTBrown** [tilt-dev/ctlptl#361]
- https://github.com/innobead/kubefire is a tool for spinning up local Kubernetes clusters using Firecracker VMs. It offers a potentially lightweight and secure alternative to `kind`/`minikube`.
- It seems like much of the functionality required for integration with `ctlptl` exists- it is merely a matter of mapping between `ctlptl`'s declarative format and the `kubefire` CLI options.

**Comment by nicks** [comment]
A couple observations:

Looks like kubefire is a thin layer of abstraction over https://github.com/weaveworks/ignite, which has been archived and is no longer maintained.

When I've chatted with ex-weaveworks engineers about this in the past, my understanding was that the ignite/flintlock approaches were focused on microvms for embedded systems (think: racks in cell phone towers or department stores). I'm not sure this tooling is ever going to be a great fit for local dev use-cases. Not a criticism, just not what it's built for.

Waiting up ctlptl registries to the microvms would be non-trivial
