### ISSUE TITLE
Error: nothing found at DockerDesktop setting "vm"

### ISSUE THREAD

**Issue by seftontycho** [tilt-dev/ctlptl#368]
Running any command that attempts to modify/get any of the settings values in the `vm` namespace.

For example running `ctlptl docker-desktop set vm.kubernetes.enabled false` gives the error `ctlptl docker-desktop: nothing found at DockerDesktop setting "vm"`.

I have tried reinstalling docker but no luck.
My ctlptl version is `vv0.8.28`.

**Comment by nicks** [comment]
Can you try upgrading ctlptl?

Docker desktop made a breaking change to the settings API, the fix for it is in ctlptl 0.8.34

https://github.com/tilt-dev/ctlptl/releases/tag/v0.8.34
