### ISSUE TITLE
Kind Kubernetes version not supported

### ISSUE THREAD

**Issue by koenmtb1** [tilt-dev/ctlptl#66]
For my development environment I need to run Kubernetes version 1.16. But when trying to set the version through ctlptl I get the message that this is not supported with Kind. Even though [this](https://kind.sigs.k8s.io/docs/user/quick-start/#setting-kubernetes-version) says otherwise. Look at the [GitHub releases page of kind](https://github.com/kubernetes-sigs/kind/releases) for the image tags

**Comment by nicks** [comment]
Thanks for the report! Ya, ctlptl should be able to support this. just need to add a bit of code to map the desired kubernetes version to the kindest/node SHA. let me see if i can add this quick

**Comment by nicks** [comment]
This should be fixed in ctlptl 0.3.1!
