### ISSUE TITLE
Enable kind v0.9.0 config fix

### ISSUE THREAD

**Issue by adamscott** [tilt-dev/ctlptl#70]
I'm having an issue with Kind about an invalid argument when unpacking an image. While searching for the issue, I found this on the [breaking changes part of the Kind release page for v0.9.0](https://github.com/kubernetes-sigs/kind/releases/tag/v0.9.0#breaking-changes):

> UPDATE: If you are hitting label key and value greater than maximum size (4096 bytes), key: containerd: invalid argument (containerd/cri#1572), then try the following KIND config:
> ```
> kind: Cluster
> apiVersion: kind.x-k8s.io/v1alpha4
> containerdConfigPatches:
> - |-
>   [plugins."io.containerd.grpc.v1.cri".containerd]
>   disable_snapshot_annotations = true
> ```

But there is no way to set custom Kind config for now, as there is this comment in the [admin_kind.go file](https://github.com/tilt-dev/ctlptl/blob/6cb903ecd61d30ccdfa2f4e98bcc121e57d6ebd2/pkg/cluster/admin_kind.go#L66).
`// TODO(nick): Let the user pass in their own Kind configuration.`

Can a fix or an option be made available? Thanks!

**Comment by nicks** [comment]
thanks for the report!

ya, i always wanted to make the Kind cluster config part of this, but was just looking for a good motivating use case!

**Comment by adamscott** [comment]
@nicks Same thing about the mount points that need to be setup in the kind config file. (do I create a new issue? or do I rename this issue for custom Kind configs?)

I forked the project (adamscott/ctlptl) to [add mountpoints and the kind fix](https://github.com/adamscott/ctlptl/blob/c3c4ecd1a84170ab43cc31bb5ba9cbaa19ba8af5/pkg/cluster/admin_kind.go#L76). I added mountPoints to the desired cluster struct, but I don't know if it's the way you want to add custom kind configs. (as I don't know if other engines need to setup mountpoints in their cluster config file)

Thanks!

**Comment by nicks** [comment]
my plan is to add a field to the Cluster API like this:

```
apiVersion: ctlptl.dev/v1alpha1
kind: Cluster
product: kind

// embedded https://github.com/kubernetes-sigs/kind/blob/master/pkg/apis/config/v1alpha4/types.go#L20
kind.v1alpha4:
  containerdConfigPatches:
  - ...
```

so ya, you'd be free to add mount points too

out of curiosity, what are you using the mount points for? i'm figuring out ways to do host mounts in a cross-cluster way, and collecting use-cases

**Comment by nicks** [comment]
(also: would you be OK with me upstreaming your mounts code? just looked at it and it seems like an awesome addition!)

**Comment by adamscott** [comment]
> out of curiosity, what are you using the mount points for? i'm figuring out ways to do host mounts in a cross-cluster way, and collecting use-cases

I'm just experimenting for the moment on a way to containerize the multiple apps we are developing at my workplace for our SaaS. As some projects are interdependent and the setup can take for up a day to new computer, even for an experienced dev. And it's kind of messy too.

I'm developing on the side, for the experiment, a CLI that setup the dev environment and create a config file. There after, I use the same CLI to trigger a "build" which creates the Tiltfile for the whole project.

I'm new to containers, so I thought to create containers that has everything to run the project, but with mount points to the source code for dev purposes.

Thinking of it, maybe it would be preferable to bake in everything and refresh the image itself on change, using Tilt watchfiles.

Still thinking about it.

> (also: would you be OK with me upstreaming your mounts code? just looked at it and it seems like an awesome addition!)

Yeah, sure!

**Comment by nicks** [comment]
Thanks, that's really helpful!

ctlptl v0.4.0 should support a kind cluster config so you can disable snapshot annotations and add mounts https://pkg.go.dev/github.com/tilt-dev/ctlptl@v0.4.0/pkg/api#Cluster. Want to add a mounts api too but want to add it in a way that will work on minikube too.
