### ISSUE TITLE
minikube example create fails on linux

### ISSUE THREAD

**Issue by friend0** [tilt-dev/ctlptl#80]
Running the example Minikube command
`ctlptl create cluster minikube --registry=ctlptl-registry --kubernetes-version=v1.18.8`
fails on Linux.
I can confirm `docker version` returns, and I can start a Minikube cluster manually.

**Comment by nicks** [comment]
Thanks for the report! I tested this with Linux so I'm not sure what's going on...

can you send along:
- The error message it fails with
- The output of `minikube version`
Thanks!

**Comment by friend0** [comment]
Disregard, this one was operator error! 
I failed to `Setup Docker as a non-root user.` on a new machine
