### ISSUE TITLE
ctlptl can't reconcile a stopped registry container

### ISSUE THREAD

**Issue by eaceaser** [tilt-dev/ctlptl#81]
If you have stopped a registry container with something like `docker stop ctlptl-registry`, then try to recreate a cluster with `ctlptl apply`, you get an opaque error message, such as:

```
❯ cat ctlptl-kind.yaml | ctlptl apply -f -
Creating registry "ctlptl-registry"...
exit status 125
```

This appears to be due to ctlptl not detecting a stopped container, executing [this command](http://github.com/tilt-dev/ctlptl/blob/a0c20e0dc74097f99947be4646cec64fd75ac2e3/pkg/registry/registry.go#L203-L204), which fails:

> docker: Error response from daemon: Conflict. The container name "/ctlptl-registry" is already in use by container "81d4e69896c373c395d28fc0fdeed1a244ed6d20b26503a3e12ad189b28cbf11". You have to remove (or rename) that container to be able to reuse that name.

Removing the container with `docker rm` clears the issue up.

**Comment by nicks** [comment]
thanks! ya, I like the idea of it automatically removing the dead registry for you
