### ISSUE TITLE
ctlptl in circleci with remote docker

### ISSUE THREAD

**Issue by nicks** [tilt-dev/ctlptl#92]
Our kind-local script has instructions on how to run in kind in circleci with a remote docker

We should support this in ctlptl as well

Once we do that, we can use ctlptl to set up the tilt integration tests

**Comment by nicks** [comment]
For reference:
https://github.com/tilt-dev/kind-local/tree/master/.circleci

**Comment by amerryma** [comment]
Hi,

Is there any progress on this? Something like this is important for us as we are attempting to have tilt run our integration tests for our k8s environment. For now, I'll be using the repository you linked.

**Comment by nicks** [comment]
@amerryma ah, i didn't realize anyone else was waiting on this, i thought it was just tilt-team! Ya, I can finish wiring this together this week...in the meantime, the bash script in the other repo should work too.

**Comment by nicks** [comment]
this should work now! I have a PR out to update Tilt to use this for integration testing on circleci. It looks like this:

```
ctlptl create cluster kind --registry=ctlptl-registry && make integration
```

There's also a ctlptl docker image now to help set it up: https://hub.docker.com/r/tiltdev/ctlptl

**Comment by amerryma** [comment]
@nicks Much appreciated! We'll work on implementing soon and come back if we have any issues. Thanks for the quick turn around on this!
